/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as TasksRouteImport } from './routes/tasks';
import { Route as SprintsRouteImport } from './routes/sprints';
import { Route as SpacesRouteImport } from './routes/spaces';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as RoomsRouteImport } from './routes/rooms';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as NotificationsRouteImport } from './routes/notifications';
import { Route as LoginRouteImport } from './routes/login';
import { Route as FriendsRouteImport } from './routes/friends';
import { Route as FocusRouteImport } from './routes/focus';
import { Route as FeedRouteImport } from './routes/feed';
import { Route as DomainsRouteImport } from './routes/domains';
import { Route as DiscoverRouteImport } from './routes/discover';
import { Route as CalendarRouteImport } from './routes/calendar';
import { Route as BoardRouteImport } from './routes/board';
import { Route as BacklogRouteImport } from './routes/backlog';
import { Route as AnalyticsRouteImport } from './routes/analytics';
import { Route as IndexRouteImport } from './routes/index';
import { Route as TasksIdRouteImport } from './routes/tasks.$id';
import { Route as SprintsIdRouteImport } from './routes/sprints.$id';
import { Route as SocialPlatformsRouteImport } from './routes/social.platforms';
import { Route as RoomsIdRouteImport } from './routes/rooms.$id';
import { Route as ProfileUidRouteImport } from './routes/profile.$uid';
import { Route as DomainsIdRouteImport } from './routes/domains.$id';
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces.$spaceId';
import { Route as SpacesSpaceIdSummaryRouteImport } from './routes/spaces.$spaceId.summary';
import { Route as SpacesSpaceIdBoardRouteImport } from './routes/spaces.$spaceId.board';
import { Route as SpacesSpaceIdBacklogRouteImport } from './routes/spaces.$spaceId.backlog';
import { Route as SpacesSpaceIdMembersRouteImport } from './routes/spaces.$spaceId.members';
const TasksRoute = TasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => rootRouteImport,
});
const SprintsRoute = SprintsRouteImport.update({
    id: '/sprints',
    path: '/sprints',
    getParentRoute: () => rootRouteImport,
});
const SpacesRoute = SpacesRouteImport.update({
    id: '/spaces',
    path: '/spaces',
    getParentRoute: () => rootRouteImport,
});
const SettingsRoute = SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => rootRouteImport,
});
const RoomsRoute = RoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => rootRouteImport,
});
const NotificationsRoute = NotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const FriendsRoute = FriendsRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => rootRouteImport,
});
const FocusRoute = FocusRouteImport.update({
    id: '/focus',
    path: '/focus',
    getParentRoute: () => rootRouteImport,
});
const FeedRoute = FeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => rootRouteImport,
});
const DomainsRoute = DomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => rootRouteImport,
});
const DiscoverRoute = DiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => rootRouteImport,
});
const CalendarRoute = CalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => rootRouteImport,
});
const BoardRoute = BoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => rootRouteImport,
});
const BacklogRoute = BacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => rootRouteImport,
});
const AnalyticsRoute = AnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const TasksIdRoute = TasksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => TasksRoute,
});
const SprintsIdRoute = SprintsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => SprintsRoute,
});
const SocialPlatformsRoute = SocialPlatformsRouteImport.update({
    id: '/social/platforms',
    path: '/social/platforms',
    getParentRoute: () => rootRouteImport,
});
const RoomsIdRoute = RoomsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => RoomsRoute,
});
const ProfileUidRoute = ProfileUidRouteImport.update({
    id: '/profile/$uid',
    path: '/profile/$uid',
    getParentRoute: () => rootRouteImport,
});
const DomainsIdRoute = DomainsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DomainsRoute,
});
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
    id: '/$spaceId',
    path: '/$spaceId',
    getParentRoute: () => SpacesRoute,
});
const SpacesSpaceIdSummaryRoute = SpacesSpaceIdSummaryRouteImport.update({
    id: '/$spaceId/summary',
    path: '/$spaceId/summary',
    getParentRoute: () => SpacesRoute,
});
const SpacesSpaceIdBoardRoute = SpacesSpaceIdBoardRouteImport.update({
    id: '/$spaceId/board',
    path: '/$spaceId/board',
    getParentRoute: () => SpacesRoute,
});
const SpacesSpaceIdBacklogRoute = SpacesSpaceIdBacklogRouteImport.update({
    id: '/$spaceId/backlog',
    path: '/$spaceId/backlog',
    getParentRoute: () => SpacesRoute,
});
const SpacesSpaceIdMembersRoute = SpacesSpaceIdMembersRouteImport.update({
    id: '/$spaceId/members',
    path: '/$spaceId/members',
    getParentRoute: () => SpacesRoute,
});
const DomainsRouteChildren = {
    DomainsIdRoute: DomainsIdRoute,
};
const DomainsRouteWithChildren = DomainsRoute._addFileChildren(DomainsRouteChildren);
const RoomsRouteChildren = {
    RoomsIdRoute: RoomsIdRoute,
};
const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren);
const SpacesRouteChildren = {
    SpacesSpaceIdRoute: SpacesSpaceIdRoute,
    SpacesSpaceIdSummaryRoute: SpacesSpaceIdSummaryRoute,
    SpacesSpaceIdBoardRoute: SpacesSpaceIdBoardRoute,
    SpacesSpaceIdBacklogRoute: SpacesSpaceIdBacklogRoute,
    SpacesSpaceIdMembersRoute: SpacesSpaceIdMembersRoute,
};
const SpacesRouteWithChildren = SpacesRoute._addFileChildren(SpacesRouteChildren);
const SprintsRouteChildren = {
    SprintsIdRoute: SprintsIdRoute,
};
const SprintsRouteWithChildren = SprintsRoute._addFileChildren(SprintsRouteChildren);
const TasksRouteChildren = {
    TasksIdRoute: TasksIdRoute,
};
const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AnalyticsRoute: AnalyticsRoute,
    BacklogRoute: BacklogRoute,
    BoardRoute: BoardRoute,
    CalendarRoute: CalendarRoute,
    DiscoverRoute: DiscoverRoute,
    DomainsRoute: DomainsRouteWithChildren,
    FeedRoute: FeedRoute,
    FocusRoute: FocusRoute,
    FriendsRoute: FriendsRoute,
    LoginRoute: LoginRoute,
    NotificationsRoute: NotificationsRoute,
    RegisterRoute: RegisterRoute,
    RoomsRoute: RoomsRouteWithChildren,
    SettingsRoute: SettingsRoute,
    SpacesRoute: SpacesRouteWithChildren,
    SprintsRoute: SprintsRouteWithChildren,
    TasksRoute: TasksRouteWithChildren,
    ProfileUidRoute: ProfileUidRoute,
    SocialPlatformsRoute: SocialPlatformsRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
