/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SprintsRouteImport } from './routes/sprints'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as SprintsIdRouteImport } from './routes/sprints.$id'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces.$spaceId'
import { Route as SocialPlatformsRouteImport } from './routes/social.platforms'
import { Route as RoomsIdRouteImport } from './routes/rooms.$id'
import { Route as ProfileUidRouteImport } from './routes/profile.$uid'
import { Route as DomainsIdRouteImport } from './routes/domains.$id'
import { Route as SpacesSpaceIdSummaryRouteImport } from './routes/spaces.$spaceId.summary'
import { Route as SpacesSpaceIdMembersRouteImport } from './routes/spaces.$spaceId.members'
import { Route as SpacesSpaceIdBoardRouteImport } from './routes/spaces.$spaceId.board'
import { Route as SpacesSpaceIdBacklogRouteImport } from './routes/spaces.$spaceId.backlog'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsRoute = SprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRoute,
} as any)
const SprintsIdRoute = SprintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SprintsRoute,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/$spaceId',
  path: '/$spaceId',
  getParentRoute: () => SpacesRoute,
} as any)
const SocialPlatformsRoute = SocialPlatformsRouteImport.update({
  id: '/social/platforms',
  path: '/social/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoomsRoute,
} as any)
const ProfileUidRoute = ProfileUidRouteImport.update({
  id: '/profile/$uid',
  path: '/profile/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIdRoute = DomainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DomainsRoute,
} as any)
const SpacesSpaceIdSummaryRoute = SpacesSpaceIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdMembersRoute = SpacesSpaceIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdBoardRoute = SpacesSpaceIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdBacklogRoute = SpacesSpaceIdBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backlog': typeof BacklogRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/domains': typeof DomainsRouteWithChildren
  '/feed': typeof FeedRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/sprints': typeof SprintsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/domains/$id': typeof DomainsIdRoute
  '/profile/$uid': typeof ProfileUidRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/social/platforms': typeof SocialPlatformsRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/sprints/$id': typeof SprintsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/spaces/$spaceId/backlog': typeof SpacesSpaceIdBacklogRoute
  '/spaces/$spaceId/board': typeof SpacesSpaceIdBoardRoute
  '/spaces/$spaceId/members': typeof SpacesSpaceIdMembersRoute
  '/spaces/$spaceId/summary': typeof SpacesSpaceIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backlog': typeof BacklogRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/domains': typeof DomainsRouteWithChildren
  '/feed': typeof FeedRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/sprints': typeof SprintsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/domains/$id': typeof DomainsIdRoute
  '/profile/$uid': typeof ProfileUidRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/social/platforms': typeof SocialPlatformsRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/sprints/$id': typeof SprintsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/spaces/$spaceId/backlog': typeof SpacesSpaceIdBacklogRoute
  '/spaces/$spaceId/board': typeof SpacesSpaceIdBoardRoute
  '/spaces/$spaceId/members': typeof SpacesSpaceIdMembersRoute
  '/spaces/$spaceId/summary': typeof SpacesSpaceIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backlog': typeof BacklogRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/domains': typeof DomainsRouteWithChildren
  '/feed': typeof FeedRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/sprints': typeof SprintsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/domains/$id': typeof DomainsIdRoute
  '/profile/$uid': typeof ProfileUidRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/social/platforms': typeof SocialPlatformsRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/sprints/$id': typeof SprintsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/spaces/$spaceId/backlog': typeof SpacesSpaceIdBacklogRoute
  '/spaces/$spaceId/board': typeof SpacesSpaceIdBoardRoute
  '/spaces/$spaceId/members': typeof SpacesSpaceIdMembersRoute
  '/spaces/$spaceId/summary': typeof SpacesSpaceIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/backlog'
    | '/board'
    | '/calendar'
    | '/discover'
    | '/domains'
    | '/feed'
    | '/focus'
    | '/friends'
    | '/login'
    | '/notifications'
    | '/register'
    | '/rooms'
    | '/settings'
    | '/spaces'
    | '/sprints'
    | '/tasks'
    | '/domains/$id'
    | '/profile/$uid'
    | '/rooms/$id'
    | '/social/platforms'
    | '/spaces/$spaceId'
    | '/sprints/$id'
    | '/tasks/$id'
    | '/spaces/$spaceId/backlog'
    | '/spaces/$spaceId/board'
    | '/spaces/$spaceId/members'
    | '/spaces/$spaceId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/backlog'
    | '/board'
    | '/calendar'
    | '/discover'
    | '/domains'
    | '/feed'
    | '/focus'
    | '/friends'
    | '/login'
    | '/notifications'
    | '/register'
    | '/rooms'
    | '/settings'
    | '/spaces'
    | '/sprints'
    | '/tasks'
    | '/domains/$id'
    | '/profile/$uid'
    | '/rooms/$id'
    | '/social/platforms'
    | '/spaces/$spaceId'
    | '/sprints/$id'
    | '/tasks/$id'
    | '/spaces/$spaceId/backlog'
    | '/spaces/$spaceId/board'
    | '/spaces/$spaceId/members'
    | '/spaces/$spaceId/summary'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/backlog'
    | '/board'
    | '/calendar'
    | '/discover'
    | '/domains'
    | '/feed'
    | '/focus'
    | '/friends'
    | '/login'
    | '/notifications'
    | '/register'
    | '/rooms'
    | '/settings'
    | '/spaces'
    | '/sprints'
    | '/tasks'
    | '/domains/$id'
    | '/profile/$uid'
    | '/rooms/$id'
    | '/social/platforms'
    | '/spaces/$spaceId'
    | '/sprints/$id'
    | '/tasks/$id'
    | '/spaces/$spaceId/backlog'
    | '/spaces/$spaceId/board'
    | '/spaces/$spaceId/members'
    | '/spaces/$spaceId/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BacklogRoute: typeof BacklogRoute
  BoardRoute: typeof BoardRoute
  CalendarRoute: typeof CalendarRoute
  DiscoverRoute: typeof DiscoverRoute
  DomainsRoute: typeof DomainsRouteWithChildren
  FeedRoute: typeof FeedRoute
  FocusRoute: typeof FocusRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SpacesRoute: typeof SpacesRouteWithChildren
  SprintsRoute: typeof SprintsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  ProfileUidRoute: typeof ProfileUidRoute
  SocialPlatformsRoute: typeof SocialPlatformsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints': {
      id: '/sprints'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof SprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/sprints/$id': {
      id: '/sprints/$id'
      path: '/$id'
      fullPath: '/sprints/$id'
      preLoaderRoute: typeof SprintsIdRouteImport
      parentRoute: typeof SprintsRoute
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/social/platforms': {
      id: '/social/platforms'
      path: '/social/platforms'
      fullPath: '/social/platforms'
      preLoaderRoute: typeof SocialPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/profile/$uid': {
      id: '/profile/$uid'
      path: '/profile/$uid'
      fullPath: '/profile/$uid'
      preLoaderRoute: typeof ProfileUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$id': {
      id: '/domains/$id'
      path: '/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof DomainsIdRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/spaces/$spaceId/summary': {
      id: '/spaces/$spaceId/summary'
      path: '/summary'
      fullPath: '/spaces/$spaceId/summary'
      preLoaderRoute: typeof SpacesSpaceIdSummaryRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/members': {
      id: '/spaces/$spaceId/members'
      path: '/members'
      fullPath: '/spaces/$spaceId/members'
      preLoaderRoute: typeof SpacesSpaceIdMembersRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/board': {
      id: '/spaces/$spaceId/board'
      path: '/board'
      fullPath: '/spaces/$spaceId/board'
      preLoaderRoute: typeof SpacesSpaceIdBoardRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/backlog': {
      id: '/spaces/$spaceId/backlog'
      path: '/backlog'
      fullPath: '/spaces/$spaceId/backlog'
      preLoaderRoute: typeof SpacesSpaceIdBacklogRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
  }
}

interface DomainsRouteChildren {
  DomainsIdRoute: typeof DomainsIdRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsIdRoute: DomainsIdRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

interface RoomsRouteChildren {
  RoomsIdRoute: typeof RoomsIdRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsIdRoute: RoomsIdRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

interface SpacesSpaceIdRouteChildren {
  SpacesSpaceIdBacklogRoute: typeof SpacesSpaceIdBacklogRoute
  SpacesSpaceIdBoardRoute: typeof SpacesSpaceIdBoardRoute
  SpacesSpaceIdMembersRoute: typeof SpacesSpaceIdMembersRoute
  SpacesSpaceIdSummaryRoute: typeof SpacesSpaceIdSummaryRoute
}

const SpacesSpaceIdRouteChildren: SpacesSpaceIdRouteChildren = {
  SpacesSpaceIdBacklogRoute: SpacesSpaceIdBacklogRoute,
  SpacesSpaceIdBoardRoute: SpacesSpaceIdBoardRoute,
  SpacesSpaceIdMembersRoute: SpacesSpaceIdMembersRoute,
  SpacesSpaceIdSummaryRoute: SpacesSpaceIdSummaryRoute,
}

const SpacesSpaceIdRouteWithChildren = SpacesSpaceIdRoute._addFileChildren(
  SpacesSpaceIdRouteChildren,
)

interface SpacesRouteChildren {
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRouteWithChildren
}

const SpacesRouteChildren: SpacesRouteChildren = {
  SpacesSpaceIdRoute: SpacesSpaceIdRouteWithChildren,
}

const SpacesRouteWithChildren =
  SpacesRoute._addFileChildren(SpacesRouteChildren)

interface SprintsRouteChildren {
  SprintsIdRoute: typeof SprintsIdRoute
}

const SprintsRouteChildren: SprintsRouteChildren = {
  SprintsIdRoute: SprintsIdRoute,
}

const SprintsRouteWithChildren =
  SprintsRoute._addFileChildren(SprintsRouteChildren)

interface TasksRouteChildren {
  TasksIdRoute: typeof TasksIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIdRoute: TasksIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BacklogRoute: BacklogRoute,
  BoardRoute: BoardRoute,
  CalendarRoute: CalendarRoute,
  DiscoverRoute: DiscoverRoute,
  DomainsRoute: DomainsRouteWithChildren,
  FeedRoute: FeedRoute,
  FocusRoute: FocusRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SpacesRoute: SpacesRouteWithChildren,
  SprintsRoute: SprintsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  ProfileUidRoute: ProfileUidRoute,
  SocialPlatformsRoute: SocialPlatformsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
